#!/bin/bash
# Github Branch

# set the work directory to script's directory
cd "$(dirname "$0")"

time=`date '+%Y-%m-%d %H:%M:%S'`;

git checkout master

wget --recursive --no-clobber --page-requisites --html-extension --convert-links --restrict-file-names=windows  --no-parent https://438560969.wixsite.com/mysite

git add .

git commit -m "Updated By: $time"

git push

